version: "3.9"
services:

  lama-mysql:
    image: mysql:8-oracle
    container_name: ${HOSTNAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqlData:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    ports:
      - 3306:3306

  lama-phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: lama-phpmyadmin
    links:
      - lama-mysql
    environment:
      PMA_HOST: ${HOSTNAME}
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 81:80
    depends_on:
      lama-mysql:
        condition: service_healthy

volumes:
  mysqlData: