version: "3.9"
services:
  lama-frontend:
    container_name: lama-frontend
    build: ../frontend
    depends_on:
      lama-backend: 
        condition: service_healthy
      lama-mysql:
        condition: service_healthy

  lama-backend:
    build: ../backend
    container_name: lama-backend
    environment:
      - HOST=lama-mysql
      - USER=${MYSQL_USER}
      - PASSWORD=${MYSQL_PASSWORD}
    links: 
      - lama-mysql
    depends_on:
      lama-mysql:
        condition: service_healthy

  lama-mysql:
    image: mysql:8-oracle
    container_name: lama-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: lama
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqlData:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  lama-phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: lama-phpmyadmin
    links:
      - lama-mysql
    environment:
      PMA_HOST: lama-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: http://localhost/pma
    depends_on:
      lama-mysql:
        condition: service_healthy

  lama-nginx:
    build: ../nginx
    container_name: lama-nginx
    links:
      - lama-frontend
      - lama-backend
      - lama-phpmyadmin
    environment:
      hostname: ${HOSTNAME}
      letsencrypt: true
    depends_on:
      - lama-frontend
      - lama-backend
      - lama-mysql
      - lama-phpmyadmin
    ports:
          - 80:80
          - 443:443
volumes:
  mysqlData: