version: "3.9"
services:
  lama-flask:
      build: 
      context: ../
      dockerfile: ./backend/Dockerfile
    container_name: lama-flask
    environment:
      - HOST=${HOSTNAME}
      - USER=${MYSQL_USER}
      - PASSWORD=${MYSQL_PASSWORD}
    links: 
      - lama-mysql
    depends_on:
      lama-mysql:
        condition: service_healthy
    ports:
      - 5000:5000
    volumes:
      - migrationsData:/app/migrations

  lama-mysql:
    image: mysql:8-oracle
    container_name: ${HOSTNAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqlData:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  lama-phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: lama-phpmyadmin
    links:
      - lama-mysql
    environment:
      PMA_HOST: ${HOSTNAME}
      PMA_PORT: ${PORT}
      PMA_ARBITRARY: 1
    ports:
      - 81:80
    depends_on:
      lama-mysql:
        condition: service_healthy

volumes:
  mysqlData:
  migrationsData: