version: "3.9"
services:
  lama-frontend:
    container_name: lama-frontend
    build:
      context: ../
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      lama-flask: 
        condition: service_healthy

  lama-flask:
    build: 
      context: ../
      dockerfile: ./backend/Dockerfile
    container_name: lama-flask
    links:
      - lama-db
    depends_on:
      lama-db:
        condition: service_healthy
    ports:
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    volumes:
      - migrationsData:/app/migrations

  lama-db:
    image: mysql:8-oracle
    container_name: lama-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysqlData:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  lama-phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: lama-phpmyadmin
    links:
      - lama-db
    environment:
      PMA_HOST: ${DB_HOSTNAME}
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 1
    ports:
      - ${PMA_PORT}:80
    depends_on:
      lama-db:
        condition: service_healthy

volumes:
  mysqlData:
  migrationsData: