version: "3.9"
services:
  lama-db:
    image: mysql:8-oracle
    container_name: ${DB_HOSTNAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mysqlData:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  lama-phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: lama-phpmyadmin
    links:
      - lama-db
    environment:
      PMA_HOST: ${DB_HOSTNAME}
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 1
    ports:
      - ${PMA_PORT}:80
    depends_on:
      lama-db:
        condition: service_healthy

volumes:
  mysqlData:
  migrationsData: