from src.routes.auth_routes import auth_routes
from src.routes.util_routes import util_routes
from src.routes.project_routes import project_routes
from src.routes.label_routes import label_routes
from src.routes.label_type_routes import label_type_routes
from src.routes.labelling_routes import labelling_routes
from src.routes.account_routes import account_routes
from src.routes.theme_routes import theme_routes
from src.routes.artifact_routes import artifact_routes
from src.routes.conflict_routes import conflict_routes
from src.routes.change_routes import change_routes